Add MHRise HZV command
ricochhet/CatBot pull request #42
Opened 2023-10-13 01:35 UTC by ricochhet

2023-10-16 05:14 UTC, Yofou requested changes
Looking good, defiantly an awesome start. you need make a few changes I commented below and feel free to do or ignore the nitpicks I gave!

one more thing if you look into the `main.kt` you need to add `add( ::Mhr )` inside the extensions dsl, otherwise the command won't exist.

2023-10-16 05:14 UTC, Yofou commented on src/main/kotlin/autocomplete/MhrMonster.kt
> +    private const val dir = "./src/main/resources/source_files/MonsterDataImages/assets/mhr"
nitpick: can you use absolute paths here, ie `src/main/resources/source_files/MonsterDataImages/assets/mhr`, both should work, but `./` can make it look like this path is relative to this file when it's not.

2023-10-16 05:14 UTC, Yofou commented on src/main/kotlin/autocomplete/MhrMonster.kt
> +        name.replace("_HZV", "") // Not sure if this'll actually work.
this does work, please remove the comment.

2023-10-16 05:14 UTC, Yofou commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +}
Do we need to handle this case?

2023-10-16 05:14 UTC, Yofou commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +    val dir = "./src/main/resources/source_files/MonsterDataImages/assets/mhr"
nitpick: same comment as above `src/main/resources/source_files/MonsterDataImages/assets/mhr
"`

2023-10-16 05:14 UTC, Yofou commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +                val monsterName = arguments.monsterName.lowercase().capitalizeWords().capitalizeDashes()
you don't need to manipulate this text here, as we already have the right format for the file. 
(so remove the lowercase, capitalWords and capitalizeDashes method)

2023-10-16 05:14 UTC, Yofou commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +                val hzv = File("$dir/monster/${monsterName}_HZV.PNG")
These file searches are case sensitive so you need  to use `.png` here all lowercase.

2023-10-16 05:14 UTC, Yofou commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +                val icon = File("$dir/monster/assets/icons/${monsterName}_Icon.PNG")
one thing here, is that there seems to be some edge cases with icons where monsterName could be `HR_{insert name here}` but the icon name is just `{insert name here}`. so can you make sure you strip out `HR_` for icons onlys

2023-10-16 05:14 UTC, Yofou commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +                files.add(NamedFile("hzv.PNG", hzv.inputStream()))
make sure you're only using the lowercase version of `.png`

2023-10-16 05:14 UTC, Yofou commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +                        url = "attachment://icon.PNG"
make sure you're only using the lowercase version of `.png` inside this embed aswell

2023-10-16 05:14 UTC, Yofou commented on src/main/resources/main.js
> +}
nitpick: can you make sure you call `blah` method after defining it. for better code readability

2023-10-16 05:16 UTC, Yofou commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +                val icon = File("$dir/monster/assets/icons/${monsterName}_Icon.PNG")
example of this is "HR_Anjanath", `HR_Anjanath_HZV.png` exists, but `HR_Anjanath_Icon.png` does not exist. but `Anjanath_Icon.png`, **does exist**. so we should be able to use that! although correct me if I'm wrong

2023-10-16 16:35 UTC, ricochhet commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +}
yes

2023-10-17 21:42 UTC, ricochhet commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +                val monsterName = arguments.monsterName.lowercase().capitalizeWords().capitalizeDashes()
Please verify this, as we use the `monsterName` variable for the embed title and the file names.

2023-10-18 01:07 UTC, Yofou commented on src/main/kotlin/extensions/mhr/Hzv.kt
> +                val monsterName = arguments.monsterName.lowercase().capitalizeWords().capitalizeDashes()
Yep, I kept the manipulation on the text for embed, but we did need to strip it for actual file search

2023-10-18 01:08 UTC, Yofou approved these changes

2023-10-18 01:22 UTC, merged